[colors.primary]
background = "#E8FDFF"
foreground = "#2D2D2D"
dim_foreground = "#607D8B"
bright_foreground = "#00838F"

[colors.normal]
black = "#607D8B"
red = "#FF69B4"
green = "#00838F"
yellow = "#006064"
blue = "#FF69B4"
magenta = "#FF69B4"
cyan = "#1A237E"
white = "#455A64"

[colors.bright]
black = "#455A64"
red = "#FF69B4"
green = "#00838F"
yellow = "#006064"
blue = "#FF69B4"
magenta = "#FF69B4"
cyan = "#1A237E"
white = "#37474F"

[colors.cursor]
text = "#E8FDFF"
cursor = "#00838F"

[colors.selection]
text = "#E8FDFF"
background = "#1A237E"
