[colors.primary]
background = "#F0F3FF"
foreground = "#211951"
dim_foreground = "#5A527F"
bright_foreground = "#836FFF"

[colors.normal]
black = "#211951"
red = "#C71F4A"
green = "#06926D"
yellow = "#B8860B"
blue = "#614FC9"
magenta = "#836FFF"
cyan = "#382988"
white = "#5A527F"

[colors.bright]
black = "#5A527F"
red = "#E63B6A"
green = "#15F5BA"
yellow = "#D4A017"
blue = "#836FFF"
magenta = "#BCB2FF"
cyan = "#614FC9"
white = "#211951"

[colors.cursor]
text = "#F0F3FF"
cursor = "#614FC9"
