set -l background F0F3FF
set -l foreground 211951
set -l selection 836FFF
set -l comment 5A527F
set -l red C71F4A
set -l orange E63B6A
set -l yellow B8860B
set -l green 06926D
set -l purple 614FC9
set -l cyan 382988
set -l mint 15F5BA

set -g fish_color_normal $foreground
set -g fish_color_command $purple
set -g fish_color_keyword $mint
set -g fish_color_redirection $foreground
set -g fish_color_end $orange
set -g fish_color_error $red
set -g fish_color_param $purple
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $mint
set -g fish_color_autosuggestion $comment

set -g fish_pager_color_progress $comment
set -g fish_pager_color_prefix $purple
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
set -g fish_pager_color_selected_background --background=$selection