set -l background E8FDFF
set -l foreground 2D2D2D
set -l selection B2EBF2
set -l comment 607D8B
set -l red FF69B4
set -l orange 00BCD4
set -l yellow 00ACC1
set -l green 0097A7
set -l purple FF69B4
set -l cyan 00BCD4
set -l pink FF69B4

set -g fish_color_normal $foreground
set -g fish_color_command $cyan
set -g fish_color_keyword $pink
set -g fish_color_redirection $foreground
set -g fish_color_end $orange
set -g fish_color_error $red
set -g fish_color_param $purple
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $pink
set -g fish_color_autosuggestion $comment

set -g fish_pager_color_progress $comment
set -g fish_pager_color_prefix $cyan
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
set -g fish_pager_color_selected_background --background=$selection
