$color = rgba(0, 188, 212, 1)
$inner_color = rgba(0, 188, 212, 0.85)
$outer_color = rgba(0, 172, 193, 1)
$font_color = rgba(45, 45, 45, 1)
$placeholder_color = rgba(96, 125, 139, 0.6)
$check_color = rgba(255, 105, 180, 1)
