background #E8FDFF
foreground #2D2D2D

selection_background #B2EBF2
selection_foreground #2D2D2D

cursor #00838F
cursor_text_color #E8FDFF

black   #607D8B
red     #FF69B4
green   #00838F
yellow  #006064
blue    #FF69B4
magenta #FF69B4
cyan    #00838F
white   #455A64

bright_black   #78909C
bright_red     #FF69B4
bright_green   #00838F
bright_yellow  #006064
bright_blue    #FF69B4
bright_magenta #FF69B4
bright_cyan    #00838F
bright_white   #37474F

mark1_foreground #E8FDFF
mark1_background #00838F
mark2_foreground #E8FDFF
mark2_background #00838F

# Cursor animation
cursor_trail 1
