background #F0F3FF
foreground #211951

selection_background #836FFF
selection_foreground #F0F3FF

cursor #614FC9
cursor_text_color #F0F3FF

black   #211951
red     #C71F4A
green   #06926D
yellow  #B8860B
blue    #614FC9
magenta #836FFF
cyan    #382988
white   #5A527F

bright_black   #5A527F
bright_red     #E63B6A
bright_green   #15F5BA
bright_yellow  #D4A017
bright_blue    #836FFF
bright_magenta #BCB2FF
bright_cyan    #614FC9
bright_white   #211951

mark1_foreground #F0F3FF
mark1_background #614FC9
mark2_foreground #F0F3FF
mark2_background #211951

# Cursor animation
cursor_trail 1
